version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'cyberpunk-red-db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db

    ports:
      - '27017-27019:27017-27019'
